# Generated by Django 3.0.7 on 2020-12-21 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='teams',
            new_name='Team',
        ),
    ]
