# Generated by Django 3.2.18 on 2023-03-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_teams_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='facebook_link',
            field=models.URLField(blank=True, default='https://www.facebook.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='linkedin_link',
            field=models.URLField(blank=True, default='https://www.linkedin.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='twitter_link',
            field=models.URLField(blank=True, default='https://twitter.com', max_length=100),
        ),
    ]
