# Generated by Django 3.2.13 on 2022-05-14 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='no_of_owners',
            field=models.CharField(default='3', max_length=255),
        ),
    ]
