# Generated by Django 3.2.18 on 2023-03-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_doors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(default='white', max_length=50),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(choices=[['Ford Supercharged 5.2-Liter V8: A Predator', 'Ford Supercharged 5.2-Liter V8: A Predator'], ['Ram High Output Turbocharged 6.7-Liter Inline-Six', 'Ram High Output Turbocharged 6.7-Liter Inline-Six'], ['Mazda SKYACTIV-G 2.0-Liter Inline-Four', 'Mazda SKYACTIV-G 2.0-Liter Inline-Four'], ['Ford High Output 3.5-Liter Twin-Turbo V6', 'Ford High Output 3.5-Liter Twin-Turbo V6'], ['Volkswagen Auto Group Twin-Turbo 4.0-Liter V8', 'Volkswagen Auto Group Twin-Turbo 4.0-Liter V8'], ['Chevrolet 6.2-Liter V8', 'Chevrolet 6.2-Liter V8'], ['Dodge Supercharged 6.2-Liter V8', 'Dodge Supercharged 6.2-Liter V8'], ['Ferrari Twin-Turbocharged 3.9-Liter V8', 'Ferrari Twin-Turbocharged 3.9-Liter V8'], ['BMW Twin-Turbo 4.4-Liter V8', 'BMW Twin-Turbo 4.4-Liter V8'], ['Audi Turbocharged 2.5-Liter Inline-Five', 'Audi Turbocharged 2.5-Liter Inline-Five']], default='Audi Turbocharged 2.5-Liter Inline-Five', max_length=255),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[['Petrol', 'Petrol'], ['Diesel', 'Diesel'], ['Electric', 'Electric'], ['Hydrogen', 'Hydrogen'], ['Hybrid', 'Hybrid'], ['Solar', 'Solar']], default='Petrol', max_length=255),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='miles',
            field=models.IntegerField(default=1618),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='car',
            name='no_of_owners',
            field=models.CharField(choices=[['1', '1'], ['2', '2'], ['3', '3'], ['4', '4'], ['5', '5']], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='passengers',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='car',
            name='state',
            field=models.CharField(choices=[['AL', 'Alabama'], ['AK', 'Alaska'], ['AZ', 'Arizona'], ['AR', 'Arkansas'], ['CA', 'California'], ['CO', 'Colorado'], ['CT', 'Connecticut'], ['DE', 'Delaware'], ['DC', 'District Of Columbia'], ['FL', 'Florida'], ['GA', 'Georgia'], ['HI', 'Hawaii'], ['ID', 'Idaho'], ['IL', 'Illinois'], ['IN', 'Indiana'], ['IA', 'Iowa'], ['KS', 'Kansas'], ['KY', 'Kentucky'], ['LA', 'Louisiana'], ['ME', 'Maine'], ['MD', 'Maryland'], ['MA', 'Massachusetts'], ['MI', 'Michigan'], ['MN', 'Minnesota'], ['MS', 'Mississippi'], ['MO', 'Missouri'], ['MT', 'Montana'], ['NE', 'Nebraska'], ['NV', 'Nevada'], ['NH', 'New Hampshire'], ['NJ', 'New Jersey'], ['NM', 'New Mexico'], ['NY', 'New York'], ['NC', 'North Carolina'], ['ND', 'North Dakota'], ['OH', 'Ohio'], ['OK', 'Oklahoma'], ['OR', 'Oregon'], ['PA', 'Pennsylvania'], ['RI', 'Rhode Island'], ['SC', 'South Carolina'], ['SD', 'South Dakota'], ['TN', 'Tennessee'], ['TX', 'Texas'], ['UT', 'Utah'], ['VT', 'Vermont'], ['VA', 'Virginia'], ['WA', 'Washington'], ['WV', 'West Virginia'], ['WI', 'Wisconsin'], ['WY', 'Wyoming']], max_length=100),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(choices=[['Manual ', 'Manual '], ['Automatic', 'Automatic '], ['Automatic-CVT', 'Automatic-CVT '], ['Automatic-SAT', 'Automatic-SAT '], ['Automatic-DCT', 'Automatic-DCT ']], default='Manual', max_length=255),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(choices=[[2000, 2000], [2001, 2001], [2002, 2002], [2003, 2003], [2004, 2004], [2005, 2005], [2006, 2006], [2007, 2007], [2008, 2008], [2009, 2009], [2010, 2010], [2011, 2011], [2012, 2012], [2013, 2013], [2014, 2014], [2015, 2015], [2016, 2016], [2017, 2017], [2018, 2018], [2019, 2019], [2020, 2020], [2021, 2021], [2022, 2022], [2023, 2023]]),
        ),
    ]
