# Generated by Django 3.2.18 on 2023-03-10 09:18

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_auto_20230310_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(choices=[['Cruise Control', 'Cruise Control'], ['Audio Interface', 'Audio Interface'], ['Airbags', 'Airbags'], ['Air Conditioning', 'Air Conditioning'], ['Seat Heating', 'Seat Heating'], ['Alarm System', 'Alarm System'], ['ParkAssist', 'ParkAssist'], ['Power Steering', 'Power Steering'], ['Reversing Camera', 'Reversing Camera'], ['Direct Fuel Injection', 'Direct Fuel Injection'], ['Auto Start/Stop', 'Auto Start/Stop'], ['Wind Deflector', 'Wind Deflector'], ['Bluetooth Handset', 'Bluetooth Handset']], max_length=195),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='car',
            name='miles',
            field=models.IntegerField(default=4279),
        ),
    ]
