# Generated by Django 3.2.18 on 2023-03-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_auto_20230310_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='body_style',
            field=models.CharField(choices=[['City Car', 'City Car'], ['Super Mini', 'Super Mini'], ['Hatchback', 'Hatchback'], ['MPV', 'MPV'], ['Saloon', 'Saloon'], ['Estate', 'Estate'], ['Coupe', 'Coupe'], ['Crossover', 'Crossover'], ['SUV', 'SUV'], ['Cabriolet', 'Cabriolet'], ['Super Car', 'Super Car']], default='Super Car', max_length=255),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='car',
            name='miles',
            field=models.IntegerField(default=4185),
        ),
    ]
